package mclachlan.brewday.ui.swing.app;

public enum ScreenKey
{
	BREWING,
	RECIPES,
	BATCHES,
	PROCESS_TEMPLATES,
	EQUIPMENT_PROFILES,
	INVENTORY_GROUP,
	INVENTORY,
	REFERENCE_DATABASE,
	WATER,
	WATER_PARAMETERS,
	FERMENTABLES,
	HOPS,
	YEAST,
	MISC,
	STYLES,
	TOOLS,
	IMPORT,
	WATER_BUILDER,
	SETTINGS,
	BREWING_SETTINGS,
	BREWING_SETTINGS_GENERAL,
	BREWING_SETTINGS_MASH,
	BREWING_SETTINGS_IBU,
	BACKEND_SETTINGS,
	BACKEND_SETTINGS_LOCAL_FILESYSTEM,
	BACKEND_SETTINGS_GIT,
	UI_SETTINGS,
	HELP,
	ABOUT
}
